site_name: EDS 123
site_description: MEDS Courses mkdocs template
site_url: https://environmental-data-science.github.io/meds-mkdocs-template/  # Update this with the actual URL
repo_url: https://github.com/environmental-data-science/meds-distill-template # Update this with the actual URL
theme:
  name: material
  custom_dir: 'overrides'
  toc:
    enabled: true
docs_dir: 'docs'
nav:
  - Home: index.md
  - Topics:
      - topic_1.md
      - topic_2.md
      - topic_3.md
      - topic_4.md
      - topic_5.md
      - topic_6.md
      - topic_7.md
      - topic_8.md
      - topic_9.md
      - topic_10.md
  - assignments.md
  - resources.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
extra_css: 
  - assets/css/theme.css
  - assets/css/extra.css
extra_javascript:
  - assets/js/set_base_url.js  # custom script to set base paths
plugins:
  - search 

