# Update this with your course (e.g. EDS XXX)
site_name: EDS 123
# Update this with your course name (e.g. Essential Python for Data Scientists)
site_description: MEDS Courses mkdocs template
# Update this with the actual URL (will be hosted at your github pages site)
site_url: https://<YOUR_USER_NAME>.github.io/<REPO_NAME>/  
# Update this with the actual URL to the repo
repo_url: https://github.com/<YOUR_USER_NAME>/<REPO_NAME>

# You shouldn't need to edit these:
theme:
  name: material
  logo: assets/images/bren_white_icon.png
  favicon: assets/images/favicon.ico
  custom_dir: 'overrides'
  toc:
    enabled: true
docs_dir: 'docs'

# Update the nav items as you build your course materials (i.e. add/remove pages)
nav:
  - Home: index.md
  - Topics:
      - topic_1.md
      - topic_2.md
      - topic_3.md
      - topic_4.md
      - topic_5.md
      - topic_6.md
      - topic_7.md
      - topic_8.md
      - topic_9.md
      - topic_10.md
  - assignments.md
  - resources.md

# You shouldn't need to edit these:
markdown_extensions:
  - toc:
      permalink: true
  - admonition
extra_css: 
  - assets/css/theme.css
  - assets/css/extra.css
extra_javascript:
  - assets/js/set_base_url.js  # custom script to set base paths
plugins:
  - search 
